# Generated by Django 4.2.6 on 2023-10-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant_types',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Response_types',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_secret', models.CharField(max_length=64)),
                ('browser_redirect', models.BooleanField(default=True)),
                ('provider_name', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=64)),
                ('redirect_uri', models.CharField(max_length=255)),
                ('implicit_consent', models.BooleanField(default=False)),
                ('grant_types', models.ManyToManyField(to='oauth_server.grant_types')),
                ('response_types', models.ManyToManyField(to='oauth_server.response_types')),
                ('scope', models.ManyToManyField(to='oauth_server.scope')),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ['provider_name'],
            },
        ),
    ]
